version: '3.7'
services:
  local-jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/srv/jekyll/
    entrypoint: ["jekyll", "serve", "--force-polling", "--livereload", "--host", "0.0.0.0"]